### ISSUE TITLE
Is this still a live project?

### ISSUE THREAD

**Issue by interstar** [VCVRack/VCV-Prototype#64] opened 2022-02-27 23:24 UTC
Is VCV Prototype still a live project?

Is it working with VCV Rack 2?

I've just installed VCV Rack 2 and I think I have Prototype installed via my library but I can't seem to see it or add it to my project.

**Comment by Cwejman** [comment] 2022-04-18 04:28
Same here, have not investigated more..

**Comment by mxa** [comment] 2022-04-20 12:39
https://github.com/VCVRack/VCV-Prototype/issues/61#issuecomment-991973835

**Comment by moon47usaco** [comment] 2022-05-22 19:10
I believe that it needs to be rebuilt for Vcv 2. Would love to have this to play around with.

I do not have the time to look further into it. Anyone else... ??

**Comment by discohead** [comment] 2022-05-27 18:20
Just chiming in that I would really love to see this updated for VCV Rack 2 Pro!

**Comment by moon47usaco** [comment] 2022-05-27 18:31
I think this was more a comprehensive solution but these have scripting abilities.

https://library.vcvrack.com/dbRackFormulaOne/FormulaOne
https://library.vcvrack.com/FrankBuss/Formula

**Comment by discohead** [comment] 2022-05-27 19:57
After quite a struggle I was able to build @sleexyz 's `v2` branch with the JS and Lua engines enabled, most of the other engines gave me trouble. https://github.com/VCVRack/VCV-Prototype/pull/62

**Comment by mxa** [comment] 2022-05-27 22:04
Can we have a word from @AndrewBelt please? Is it wanted that this module works in rack2? Is there a guideline somewhere what changed and needs adaptation? API changes?

**Comment by AndrewBelt** [comment] 2022-05-28 00:03
>Is it working with VCV Rack 2?

I haven't tried compiling Prototype for Rack 2 yet, so I'm not sure. If I remember when I'm at the office, I can give it a try.

**Comment by discohead** [comment] 2022-05-28 00:04
@AndrewBelt This PR is needed: https://github.com/VCVRack/VCV-Prototype/pull/62

**Comment by mountwebs** [comment] 2022-08-08 19:40
It would be so awesome to have this module in working vcv2! Is there any progress on this?

**Comment by Simon-L** [comment] 2022-09-10 13:11
Indeed #62 is needed.

I only needed Lua and I got it to compile and run on Linux, what languages/engines were you interested in?

**Comment by jaffasplaffa** [comment] 2022-09-17 22:03
Yeah, I am really missing Prototype a lot for VCV2. I use mostly the Pure Data engine.

I did write support a while ago and got this answer:
Hi,
 
Sorry for the delay as we have been dealing with a large volume of support requests.
 
Some work has been done on VCV Prototype to update it for VCV Rack 2, but it isn't ready yet. We hope to have it updated soon but we currently don't have a release date for you.

**Comment by porres** [comment] 2023-02-02 16:11
So what's going on? Would really like to use pd in vcv 2

**Comment by jaffasplaffa** [comment] 2023-02-05 14:59
@AndrewBelt 

Did you try to compile it?

**Comment by danielatsherpack** [comment] 2023-02-13 17:05
Dogpiling on this issue like everyone else. Prototype is the main attraction for me to even try VCV, as I am looking to expand something I wrote in PureData.

**Comment by JerrySievert** [comment] 2023-02-13 18:21
can I just stop and note that while @AndrewBelt put out the first version of this, it was expanded on by an unaffiliated, disparate group of volunteer developers each with specific specialties.

they did this mostly to scratch their own itches, not to productize a full-fledged product.

if it's so very important, perhaps talk to the developers that contributed, maybe even provide sponsorships for the work.  or, better yet, help @AndrewBelt come up with a monetization strategy for it.

otherwise, it stays, as an unsupported, volunteer-led module that could end up dead.

**Comment by porres** [comment] 2023-02-13 18:32
@JerrySievert , yes, developers helped with the protoype module and were crowdly funded, I was one of the people who funded by the way, and would hate to see this go to waste die after having supported it.

Now, @mxa led the project for embedding Pd into prototype and was part of this discussion asking what needed to be done, see https://github.com/VCVRack/VCV-Prototype/issues/64#issuecomment-1140069921

The reality, as it seems, is not that we need a new funding and re-development (as no one really brought this up), but that @AndrewBelt seems to have this quite low on his priority list and we're all here wondering and asking what's the deal and what is the problem without a proper feedback. This is the last feedback from the may 2022 https://github.com/VCVRack/VCV-Prototype/issues/64#issuecomment-1140110959

If new funding is what is actually needed, we need to hear from andrew anyway, but I do have a feeling it is supposed to be much easier and just adapt the module to compile and work on the new version.

**Comment by JerrySievert** [comment] 2023-02-13 18:34
@porres as someone who contributed, this is the first time I've seen anything about me being "crowdly" funded, or funded at all for this.  not sure what you funded, but it definitely wasn't any of the code I was responsible for.

**Comment by porres** [comment] 2023-02-13 18:37
> not sure what you funded

Embedding Pd into prototype, like I said. Did you work specifically on that with @mxa?

**Comment by JerrySievert** [comment] 2023-02-13 18:43
@porres like the other developers who did the bulk of the work on this module, I acted as an advisor, for free.

I'm sorry that you paid money to a developer for a feature and that feature has not been kept up to date, but the bulk of the development of this module, was not done by a single developer, and I highly doubt that any other of the developers who have worked on this module shared in whatever funding you provided, as a major contributor, I did not, nor am I asking for any funding (tbh, I'd simply reject the offer for this project).

> Embedding Pd into prototype, like I said.

what you said was:

> yes, developers helped with the protoype module and were crowdly funded, I was one of the people who funded

and as I noted, whatever you paid for did not pay for the development or maintenance of this module in general.

please remember that before tarring those who contributed their code, time, and expertise for _free_ with that same brush.

**Comment by porres** [comment] 2023-02-13 18:49
> whatever you paid for did not pay for the development or maintenance of this module in general.

yes, my phrasing was confusing, sorry.

> I'm sorry that you paid money to a developer for a feature and that feature has not been kept up to date,

The bottle neck is not this feature (libpd/pure data support), but the whole module which isn't available. I am not disappointed with the people I contributed/funded as I understand it is not their fault this module has been kind of discarded (at least so far). On the other hand, I have to say I was expecting at least some feedback on what's going on and what's holding this back...

**Comment by porres** [comment] 2023-02-13 18:54
By the way, I'm not a VCV user, but a main collaborator to Pure Data... this is why I helped. Just wanted to see Pd running in VCV as another possibility for it. I understand this is a feature others are interested in as well.

**Comment by mxa** [comment] 2023-02-13 19:01
I need to clarify something: We are very grateful for the generous support we got from the VCV community to implement libpd support to VCV prototype. It helped us to stay afloat in a difficult moment. I still feel responsible for libpd support in VCV prototype and will try to make sure it keeps running as my time and capabilities permit. Most of the code is from my partner @clwe and I think he would agree. But making sure the Prototype module itself is still running in newer Rack versions is defensively out of our scope. Here the core VCV team is in responsibility.

**Comment by JerrySievert** [comment] 2023-02-13 19:02
@porres great, then please contribute!  not money, but code and time.

I tried between responses and can't even get the pd code to compile locally (macOS), so it definitely looks like some work on it is sorely needed.

good luck, I am stepping away from this conversation.

my advice and suggestion is to create a new PD specific issue, and work with the developers that you funded to get it up and running.  if/when there are issues that touch all of the rest of the developers that have worked on this module, perhaps some or all of us will have time and inclination to inject our expertise.

or, perhaps it is time for someone to create a PD specific module and remove it and its dependencies from this module.

**Comment by porres** [comment] 2023-02-13 19:15
> please contribute! not money, but code and time.

I can only contribute money for this, and would gladly do it again if that's the case.

> my advice and suggestion is to create a new PD specific issue

It seems there's a lot of noise here. The module doesn't run on VCV2, that is the point as I see it. Somehow you make it seem that the module runs and that the problem is the Pd support. It is not what I've been saying and Max has also pointed the issue being specific to the VCV core team. 

> if/when there are issues that touch all of the rest of the developers that have worked on this module, perhaps some or all of us will have time and inclination to inject our expertise.

again, there seems to be a misunderstanding of the issue here.

> perhaps it is time for someone to create a PD specific module and remove it and its dependencies from this module.

again, either a misunderstanding or a suggestion that would mean that the prototype module would be officially discontinued and we'd have to start from scratch and work on something just for Pd...

**Comment by porres** [comment] 2023-02-13 19:32
> I can only contribute money for this, and would gladly do it again if that's the case.

though I'd have to say that I'd expect that once this module was created and working in VCV 1.0 that it would continue to be supported in further versions, specially if prior funding was done for one of its features and it got delivered. I hope @AndrewBelt takes this into consideration and gives this some priority without the requirement of further funds.

**Comment by JerrySievert** [comment] 2023-02-13 19:41
just one note:  PD is one of *6* language plugins, and afaik, the only one that took in _any_ community funding directly.

I doubt that PD writing their own module would "discontinue" the other 5 languages in this module.

I will quickly say that as I understand it, any major contributor has the permissions in the repo to move forward any additional development, without having to directly wait for @AndrewBelt.  plus, any other contributors are well-known, since all development was done in the open, so can likely easily be reached for discussion.

if it's a feature you want, talk to the person/people responsible for that feature, but I still believe that this module would be better off if the PD functionality were forked, personally.

**Comment by porres** [comment] 2023-02-13 20:04
> I doubt that PD writing their own module would "discontinue" the other 5 languages in this module.

I am and was aware Pd is only 1 out of 6 languages supported, I was also always aware it was the only one funded, I never meant to imply something different like the whole thing being funded and if my phrasing was ambiguous I already clarified and apologized for. Now, would you please make it clear you understand that the module has been discontinued for ALL 6 languages as it doesn't work on VCV 2.0? I don't understand the point of what you've been saying and I can only presume this isn't clear somehow from all you've been saying.

We don't even know what and if anything needs to be done for libpd to keep working, as the whole module has been discarded. The developers of libpd already said that whenever this module gets supported again, they will work on it to make sure libpd keeps functional... Now, forget about Pd, say I want the module cause I wanna do some  QuickJS (JavaScript) that you worked on. How can I get this module on VCV 2.0 so I can use it?

This is what people are asking here. Is this a live project? Will it ever work again on VCV 2.0 and further versions? So far, no one from the VCV team or those who originally worked on this module have given a clear answer why is this not working anymore and what's holding it back. First inquiries about it are from late 2021... last answer shows that Andre hadn't even tried compiling it for VCV 2.0 yet... see https://github.com/VCVRack/VCV-Prototype/issues/64#issuecomment-1140110959 I already reffered to.

**Comment by JerrySievert** [comment] 2023-02-13 20:48
> Now, forget about Pd, say I want the module cause I wanna do some QuickJS (JavaScript) that you worked on. How can I get this module on VCV 2.0 so I can use it?

here's what worked for me:

* checked out the source
* switched to the `v2` branch
* disabled all but `QUICKJS` in `Makefile`
* ran `git submodule update --init --recursive`
* ran `make dep`
* ran `make`
* ran `make install`

compiled cleanly, and is available to me.

seems like VCVRack v2 support isn't a very specific issue.  again, I highly recommend you create a PD issue, and discuss the PD specific issues there, since it seems that the `v2` branch, at least for some language extensions, appears to work.  if you have specific difficulties building it that are not directly related to PD, then I recommend you create issues for those specific components.

**Comment by porres** [comment] 2023-02-13 21:55
Nice that you can compile, that's great, but you have only compiled QUICKJS. The whole point of this issue is that this module isn't supported anymore for download and somehow you miss this and make it about something else. I wasn't questioning if you could compile with QUICKJS support, I tried to ask "_How can I get this module on VCV 2.0 so I can use it?_", which means, what if I wanted to download and use this module for QUICKJS or whatever it provides... 

This one should be really simple, but it's getting way too complicated, out of focus and tiresome. This is my last ditch effort. 

> seems like VCVRack v2 support isn't a very specific issue

People can't download this module anymore in VCV 2.0 so we're asking what is the deal, if there is interest to keep supporting it and making it available for download in https://library.vcvrack.com/ or what. Some people can't dig further so the best to be done is just asking, what still makes this a valid ticket.

Yes, we don't know if there's anything specific in the way of supporting this module with all its features and questions about it have extensively been made. No, we don't have a specific answer yet. We don't know if the problem is that there are any compiling issues, be with pdlib support or whatever. Maybe there's no problem at all in compiling with all of its features (so the real problem would be simply not caring at all about providing this anymore...)

Can you answer why is this module not available for download and not supported anymore? If you can't, that's fine, but please just wish us good luck and step away (like you suggested you'd do). It really seems you're here just to digress and try to make this invalid, complicated, and about something else, when it should be really really simple and straightforward. Sorry if I sound harsh, but after so many messages going round in circles, that's the best I can do.

It seems we started on the wrong foot, you felt I was being disrespectful/ungrateful for people who worked on this for free or something. It wasn't my intention at all, I tried explaining it. I do have to say though that I feel once the VCV team called a crowd funding for a feature in this module that it is disrespectful for those who supported it to just let it rot and not make it available anymore. 

Once again, the problem is not that those who were funded to add libpd support to this module don't feel like working on it anymore, the focus of this issue is not about this at all. It is not their responsibility to support the whole module with all of its feature and upload and make it available to download for VCV 2.0 users. There's no specific issue about Pd to open at all at this point.

But anyway, thanks in clarifying this module should compile just fine with QUICKJS support.

**Comment by JerrySievert** [comment] 2023-02-13 22:17
> People can't download this module anymore in VCV 2.0 so we're asking what is the deal, if there is interest to keep supporting

this is specifically a module for prototyping.  most of its usage appears to have been by developers who wish to develop their own modules, and has been great for that usage.  I originally contributed to this module because I had a similar module and did not want to duplicate effort, and it has saved me a lot of time when prototyping modules for free release, for sale, and for my personal projects.

so, from that aspect, it appears that it has continued to be supported, and is working as intended.

> Can you answer why is this module not available for download and not supported anymore?

those are 2 or 3 very different questions, depending on how leading you want to be.  as far as being available for download, all source is available, and the module itself appears to have been updated for rack 2.0.  whether it is in the library or not is not up to me - anyone can fork the module and make it available under a different name as long as they continue to abide by the `LICENSE`.

as far as not being supported?  I have yet to see any indication of that: there have been updates in the v2 branch that make it compile and work as designed in rack 2.0; plus you have contributors responding in thread that it is working for them and that if you are having specific language support issue then you should open up specific issues: "it doesn't work" is not a specific issue.  it appears to work for its intended purpose - it acts as a base platform to expose specific language support for developers that wish to make language support available to prototype.

>  I do have to say though that I feel once the VCV team called a crowd funding for a feature in this module that it is disrespectful for those who supported it to just let it rot and not make it available anymore.

I'm not part of the vcv team, and as I stated before know nothing about the crowdfunding effort, nor have I benefitted.  I am just noting that the module itself does indeed work with rack 2.0, and if there are specific aspect that do not then you **need** to open an issue for them.  complaining that "nothing works" when your complaint is that it is not being distributed in the library does not a software development issue make.

> There's no specific issue about Pd to open at all at this point.

for me: PD module doesn't compile, but I have already stated that the PD module not compiling is not an issue for me, as there are already 5 other language plugins to choose from.  if that is a problem for you, once again, I _STRONGLY_ recommend you open an issue for your specific compilation problems.

> But anyway, thanks in clarifying this module should compile just fine with QUICKJS support.

you're absolutely welcome, but to me it just underscores that it is not a code issue for the base vcv-prototype module, and that you either need to take it up directly with the PD developers who were directly part of the crowdfunding, or if the problem specifically is that you personally cannot compile it then either put in a direct support request with VCV, or open an issue as to why you cannot compile it.

if you're looking to have it distributed as part of the main VCV libraries, then you have 3 options:

* fork it and add it yourself while complying with the license
* contact vcv support
* open a distribution specific issue for the v2 code to be compiled and made part of the vcv library

all of that said, I am going to close this issue, as it has already been determined that since this issue was opened, there have been meaningful commits to make sure that this code does indeed compile and work with rack v2.0, and thus it is indeed still _live project_.

**Closed as completed by JerrySievert** 2023-02-13 22:17 UTC

**Comment by jaffasplaffa** [comment] 2023-02-13 22:31
Been thinking about an option, which could work in using PD directly in VCV2:
- Get the VST plugin host for VCV2, which is 30$: https://library.vcvrack.com/VCV-Host/Host 
- Use PlugData as a VST, inside VCV2.

Don't have the VCV2 plugin host, so would have to splash out the 30$ to try it out. 

Might ask in VCV2/Pure Data Facebook groups to see if anyone tried that setup, before purchasing the plugin host.

But I guess it could work :)

**Comment by porres** [comment] 2023-02-13 23:04
> open a distribution specific issue for the v2 code to be compiled and made part of the vcv library

I don't understand what this means, should and could we open a new issue here on this repository asking for prototype to be compiled and made part of the vcv library for download? Let me know please. 

The idea to run plugdata should work, but it's not free/open source and not the real point here. And even if we sort out prototype running libpd, the problem is making it easily available and downloadable as a library at https://library.vcvrack.com/ ... The thing is, this thing was easily available once for installation at https://vcvrack.com/Prototype it was easy to get it running on VCV 1.0, it is not anymore - even though it is arguably "alive" depending on how you see it.

If the mentality is that this is not a tool for "regular users", in other words, if accessibility is not a concern, maybe Pure Data should really detach from prototype indeed and we have to think of a separate module so it can be made available for download. Accessibility is a big concern for Pd. Hopefully, at every new release cycle, the module could get updated to the latest version and this shows up in a changelog or something.

I'd still like to hear @AndrewBelt on this one, as he was the one who first wanted to add support for Pd and asked people to fund this feature - and he's also part of the VCV team and the development of VCV prototype, right?

> for me: PD module doesn't compile, but I have already stated that the PD module not compiling is not an issue for me, as there are already 5 other language plugins to choose from. 

So let's clarify. Can you compile for all others but Pd? 

Were you ever able to compile it with libpd support? And if so, what is the issue you get when compiling with Pd support?

thanks

**Comment by JerrySievert** [comment] 2023-02-13 23:12
> Accessibility is a big concern for Pd. Hopefully, at every new release cycle, the module could get updated to the latest version and this shows up in a changelog or something.

you're asking for someone to build and maintain a module for PD usage specifically.  you will have to talk to those that you spent money sponsoring or the main VCV team for that, as the various maintainers of this repo are not responsible for that, and as one of the various maintainers of this repo I am specifically responding to the original issue.

I closed the issue because it has been answered.

if you wish to continue, I have made multiple suggestions.

**Comment by porres** [comment] 2023-02-13 23:47
> you're asking for someone to build and maintain a module for PD usage specifically.

No... I did not, I wonder how you were able to reach this conclusion, but at this point I am not surprised.

I just mentioned that accessibility for Pd is important and you're showing that it is not the mentality here. If that's the case, I made the remark that it is indeed probably best to detach Pd from this project. Should I quote myself again? Should you try and read it back? I'll just rephrase it again since you didn't get it. For Pd, it is important that libpd projects get updated and are made available at every Pd release for users. Pd users shouldn't bother to compile themselves, ideally. So, how are we supposed to do this if this project isn't ever gonna be made available for download? Don't answer, it's a rhetorical question.

But if this is made available for everyone, there's the possibility to work on updating it with a changelog or something...

At this point, the issue was just clarifying what should be done to make this easily available for users, but anyway, I have to say it was fascinating how you kept thinking how the issue was either about you, about Pd or about me asking you or other people to work for Pd because I was part of the crowd funding. I see you got this in your head and I wonder if there'd be anything to be done to get it out... probably not...

> if you wish to continue, I have made multiple suggestions.

Yeah, it wasn't clear for me. I made a simple question to clarify it, you're not answering it saying you already did it. Cool. Awesome. You also did not answer other questions. Great. Thanks a bunch. If arguing about new stuff is all we can have, I'm out.

I will just assume we can't open an issue on this repository about having this available in the library or not. I Already opened a new issue here for that https://github.com/VCVRack/library/issues/756 

If others who were part of this thread would like to see prototype as a library download, please join the new discussion. If a new thread can be made here about making it available for download as a library, some one else can open it.

cheers

**Comment by clwe** [comment] 2023-02-14 11:14
﻿Hello there, I just read through the thread. If this is just a compilation issue — meaning I only need to update the makefile, then I’d be happy to do that. In the past I thought the API has been discontinued and a new API needs to be written first. But if the quickjs engine compiles and it still uses the old API then this clearly indicates it’s only a makefile issue. I hope I find some time for that next week. Greetings, Clemens Wegener

**Comment by porres** [comment] 2023-02-14 14:03
> if the quickjs engine compiles and it still uses the old API then this clearly indicates it’s only a makefile issue. I hope I find some time for that next week

Great, since this is closed and all, I opened a fresh new issue so you can give us feedback there (EDIT: actual new issue is https://github.com/VCVRack/VCV-Prototype/issues/66 - not "https://github.com/VCVRack/library/issues/758" ) I would also like to discuss over there the possibility of compiling this with some Pd externals (like ELSE/Cyclone), which run in plugdata and is also based on libpd (so no need to pay for a plugin host).

>  I thought the API has been discontinued and a new API needs to be written first.

Yeah, things weren't really clear. Last information and official statement from VCV support (brought by @Jaffasplaffa) said this needed "more work for VCV 2.0" and that "they" would get to it at some point. That was vague, nothing really happened since then, and I assumed similarly.

I'm bummed this issue got closed with no further clarification on what was going on... With information from the new issue I opened on the library repository, maybe Support meant it can't be built with https://github.com/VCVRack/rack-plugin-toolchain - used for the open-source modules submitted to the repo. Now I'm in touch with Support about this specifically. No answer yet but whenever I hear back I'll give feedback on this closed issue - because my new issue on the library repo was also closed and this one has more people engaged and was the "original one". So, for others here interested in this, I hope to come back with new information about the issue of making this available for 2.0 actually being resolved.

**Comment by interstar** [comment] 2023-02-14 16:52
Just to point out that PlugData DOES work as a VST in VCV 2.0 in Windows. I'm trying it now. And it seems fine.

AFAICT PlugData is itself, GPL3. VCV still has an open license, so the only "non-open" bit of this is the VST Host module in VCV which isn't FLOSS.

Obviously it would be nice if it were. Or if there were some other VST host module that is FLOSS.

But ultimately I think that the longer the whole chain of converters from one standard to another, the more likely it is for something to go wrong. Given that both PD and VCV are pretty widely used at this point, undoubtedly the best outcome would be for there to be a direct PD module for VCV. That seems to be in everyone's interest. And I'd love to see the core VCV and PD teams recognise this and get together to make it happen.

There seems to be a lot of talking past and irritation in this thread. But AFAICT as a normal user just looking at this,

1) VCV team took crowdfunding money to make Prototype.  (Which is a platform on which you could implement PD)

2) Somewhere in the transition to VCV2.0 Prototype development broke. And right now it isn't a big priority for them to fix it. Certainly there's no urgency to get a working version into the standard library of modules available.

That seems perfectly understandable. And VCV team obviously need to focus their resources on what is most useful and sustainable for them.

OTOH, I think communication could be better here. Mainly people are just asking for some clarity on what VCV's plan / intention for Prototype.

It doesn't seem it should be hard for VCV to just tell us outright whether :

1) "Prototype has been abandoned. There's no plan to fix it and get it into the standard library."
2) "Prototype is still a live project and we hope to have it ready by XX/YY/202Z"
3) "We'd really love to get Prototype back up, but we don't have the resources right now. We're really sorry about this. But we'll tell you if and when we can finally get back to it"
4) "We think Prototype is great. But we're sorry, we don't have the resources. However we're hoping that the community will pick this up and fix it and we'd love to help with that by at least XXXX"

Any of these 4 would, I think, would be a satisfactory. The frustration is in not-knowing which of these they're really thinking.

**Comment by porres** [comment] 2023-02-14 17:07
My new issue on the library repository shows there's some interest, so it's not like it's abandoned. Still waiting for better feedback though.

If we get prototype with ELSE and Cyclone, I don't see why one would want to use plugdata inside a paid plugin host. I hope we can make it.

**Comment by mxa** [comment] 2023-02-14 17:32
> * VCV team took crowdfunding money to make Prototype.  (Which is a platform on which you could implement PD)
> 
> * Somewhere in the transition to VCV2.0 Prototype development broke. And right now it isn't a big priority for them to fix it. Certainly there's no urgency to get a working version into the standard library of modules available.

I need to clarify this, as it isn't accurate. The VCV team developed the Prototype module and then there were different crowdfundings to develop integrations of other languages into the existing prototype module. With the advent of Rack2, Prototype did not compile any more, and there is simply a lack of direction wether the existence of Prototype in Rack2 is something the Rack developers desire or not. If Prototype runs in Rack2 (and is available and installable from within Rack2) then the precondition is met so that individual language supports can update their adapters if needed. Speaking for the Pd part, that's something we can look into next week. A little more guidance about the general fate of the prototype module would be much appreciated.

**Comment by porres** [comment] 2023-02-14 18:55
> Speaking for the Pd part, that's something we can look into next week

for the record, someone already compiled it just fine for windows, see https://github.com/VCVRack/VCV-Prototype/issues/66 so I guess there's not much to worry on this.

> A little more guidance about the general fate of the prototype module would be much appreciated

this seems to be the issue that'll stick, hopefully not for long

**Comment by porres** [comment] 2023-02-14 19:14
As long as we're talking about integration alternatives, here's another idea. Once can use 'cardinal' - https://github.com/DISTRHO/Cardinal - as a plugin and open it inside Pd vanilla with the [vstplugin~] external

**Comment by porres** [comment] 2023-02-25 05:53
not happy to say that, until now, no answer from support other than the email they'd look into whatever I wrote and would eventually get back to me "soon"...

**Comment by modlfo** [comment] 2023-02-25 10:46
I have done some work to fix the Vult and LuaJIT engines. I have tested my changes on Linux and Mac but I did not tested Windows. If anyone with a working windows machine can test them it would be great.

**Comment by dizzisound** [comment] 2023-02-25 14:58
Hi,
I tested the _LuaJIT/Vult_ build of VCV-Prototype (branch `v2`) on Windows 10/Msys2 and it succesfully compiles, with the following tricks:

1) 
I had to fix again the line 507 in `Prototype.cpp`:
https://github.com/VCVRack/VCV-Prototype/blob/739c0f5e90f3df8d7910b32fc0f58935f212d17d/src/Prototype.cpp#L507
with this line:
`std::wstring commandW = string::UTF8toUTF16(command); `
this fix was also suggested in this issue: 
https://github.com/VCVRack/VCV-Prototype/issues/63
but no pull-request followed the issue.
It is mandatory for a successfull Windows build.

2)
I had to rescue the _Entropia File System Watcher_ dependency target section from this merge from @mxa :
https://github.com/VCVRack/VCV-Prototype/commit/7cb75fda2faffb5b2b469cec1cc6183fcd1d7af0
as this effectively fixes an issue under Windows.

3)
In the VCV-Prototype `Makefile`, I had to turn off the Faust and Supercollider build flags, as these builds still give issues on my Windows system.
So, I ended up with the following flags setup:
```
DUKTAPE ?= 0
QUICKJS ?= 1
LUAJIT ?= 1
PYTHON ?= 0
SUPERCOLLIDER ?= 0
VULT ?= 1
LIBPD ?= 0
FAUST ?= 0
```
	
Again, I dropped the installable plugin (with the Vult engine enabled) on my Google drive, for anyone willing to try it out:
https://drive.google.com/drive/folders/1sTeHIuATPrEkTwb8fpv-vZJXsGEoBT_H?usp=sharing

**Comment by modlfo** [comment] 2023-02-25 15:51
I have applied the fixes suggested and I was able of compiling and testing on Windows.

**Comment by AndrewBelt** [comment] 2023-02-26 19:47
I apologize, I didn't realize people still had write access to this repo. I've had an idea about a complete overhaul of this plugin for Rack 2, but I haven't have time to think about it much recently and I'm worried that commits by others on the `v2` branch will create lots of confusion with users and myself.

Since this plugin is open-source, anyone is welcome to fork and rename the plugin, but I want to leave *VCV Prototype* as-is for now until I have more time to think about it. When I have time, I'll solve several issues with the plugin's design/functionality that many users have complained about. Unfortunately this redesign will break patch compatibility with Prototype v1, so I'd rather users not use an unofficial Prototype v2, since a redesign will create even more confusion and breakage of patches.

**Comment by AndrewBelt** [comment] 2023-02-26 20:09
Okay, I've moved all recent `v2` commits by @mxa, @modlfo, and @SteveRussell33 to a new branch `v2-tmp`, so fork from this branch if you'd like to make a new Rack plugin from VCV Prototype's code.

Once I have more time, I'll redesign VCV Prototype to fix its major design issues, but I want to make sure that 1) the code hasn't changed significantly since Prototype v1, and 2) there aren't thousands of people using unofficial builds in Rack 2 that will be mad about an overhaul breaking their patches.

**Comment by porres** [comment] 2023-02-26 21:18
So the answer is that this is kinda dead after all, but it's great news that there are plans to have it reincarnated in a new format for VCV 2 :) 

Given this scenario, we may think about creating a module just for Pd

**Comment by SteveRussell33** [comment] 2023-02-26 21:41
As Andrew has created the ```v2-tmp``` branch, you can download/fork this branch and build successfully with four engines enabled (JS/Lua/Vult/PD) or turn off the others and just leave PD enabled if you want.

**Comment by porres** [comment] 2023-02-26 23:11
Sure, I know, but the idea is to maybe just create a new module just for Pd in the meantime and try to build it with support for the Cyclone and ELSE external libraries, hopefully we can collaborate and bring the same features to the new prototype module when it comes out

**Comment by SteveRussell33** [comment] 2023-02-26 23:27
Sure, sounds good!

**Comment by jaffasplaffa** [comment] 2023-03-04 11:33
> Okay, I've moved all recent `v2` commits by @mxa, @modlfo, and @SteveRussell33 to a new branch `v2-tmp`, so fork from this branch if you'd like to make a new Rack plugin from VCV Prototype's code.
> 
> Once I have more time, I'll redesign VCV Prototype to fix its major design issues, but I want to make sure that 

Sounds great @AndrewBelt !

Would you consider adding some more knobs and buttons?

Like 16 buttons and 16 knobs would be really great. That would fit really great for making sequencers and the likes :)

**Comment by wyan** [comment] 2026-03-18 20:51
It's been three years since this conversation, is the project abandoned at this point?

**Comment by porres** [comment] 2026-03-18 20:56
More than ever I need this project to be a reality, but I guess it's up to @AndrewBelt ?

**Comment by AndrewBelt** [comment] 2026-03-19 06:02
Rack 3 will likely include a Javascript, Lua, etc runtime, so if VCV Prototype was released it would be obsolete after Rack 3 is released.

**Comment by porres** [comment] 2026-03-19 06:46
@AndrewBelt I get that the idea of "Prototype" would be obsolete because it was a way to have code in JS and LUA and I guess now there's another way of doing it... 

But note that prototype also ran Pd patches... and I guess you didn't mean it, but please don't say Pd would be 'obsolete' with java or lua, they're completely different languages. I guess you could say there are other solutions that you find "better" or more interesting to invest on...

I'm a Pd developer and have been working with it for over 20 years. I don't know Lua, I don't know Javascript. I'd just like to run my patches via libpd inside VCV Racks. I think there are others like me... as you can see in this issue, I was really interested in this and even helped a bit with money to add Pd support. I'd still like to see a module that could run Pd patches. I'm a better programmer these days, I could try and help, even do it myself if I have correct guidelines and a proper guidance.

What do you say?

**Comment by AndrewBelt** [comment] 2026-03-19 08:06
Yeah, a different plugin could load PureData patches. Rack 3 wouldn't be able to load them.

**Comment by porres** [comment] 2026-03-19 08:52
@AndrewBelt yeah, sure, cool. What about some guidance and guidelines?

maybe I can check the work that has been done in here by @mxa and others, strip it down and try to generate a single plugin. What about the API changes from 1 to 2? And now what about version 3, any changes I need to be aware? What is the way to do if someone just joining the party and wants to develop for VCV racks?

cheers

**Comment by wyan** [comment] 2026-03-19 10:44
> Rack 3 will likely include a Javascript, Lua, etc runtime, so if VCV Prototype was released it would be obsolete after Rack 3 is released.

That's great news! Is version 3 coming up soon then?

**Comment by porres** [comment] 2026-03-19 18:37
Ok, I forked this, stripped down just for the Pd engine and made it work in VCV 2, see https://github.com/porres/VCV-Prototype/releases/tag/v2.0-test

I will now start another project based on this with a different name and build more on it

**Comment by porres** [comment] 2026-03-19 21:39
@AndrewBelt please check this out, if it is ok and if we can publish it for others to download and test https://github.com/VCVRack/library/issues/893
